protected/models/PersonDraft.php
<?php

/**
 * This is the model class for table "person_draft".
 *
 * The followings are the available columns in table 'person_draft':
 * @property integer $id
 * @property string $firstName
 * @property string $middleName
 * @property string $lastName
 * @property string $birthDate
 * @property string $deathDate
 * @property string $contact
 * @property string $career
 * @property string $observations
 * @property integer $priority
 * @property boolean $is_student
 * @property boolean $is_professor
 * @property boolean $is_employee
 *
 * The followings are the available model relations:
 * @property EmployeeDraft[] $employeeDrafts
 * @property ProfessorDraft[] $professorDrafts
 * @property StudentDraft[] $studentDrafts
 */
class PersonDraft extends CActiveRecord
{
        public $name_search;
        public $isStudent;
        public $isProfessor;
        public $isEmployee;
        
        public $verifyCode;
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'person_draft';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('firstName, lastName', 'required'),
			array('priority', 'numerical', 'integerOnly'=>true),
			array('firstName, lastName', 'length', 'max'=>50),
			array('middleName, contact', 'length', 'max'=>100),
                        array('birthDate, deathDate','safe'),
			array('career, observations', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, firstName, middleName, lastName, birthDate, deathDate, contact, career, observations, priority, is_student,is_professor,is_employee, name_search, isStudent,isEmployee,isProfessor', 'safe', 'on'=>'search'),
                        // verifyCode needs to be entered correctly
			array('verifyCode', 'captcha', 'allowEmpty'=>!CCaptcha::checkRequirements()),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'employees' => array(self::HAS_MANY, 'EmployeeDraft', 'idPerson'),
			'professors' => array(self::HAS_MANY, 'ProfessorDraft', 'idPerson'),
			'students' => array(self::HAS_MANY, 'StudentDraft', 'idPerson'),
                        'firstEmployee' => array(self::HAS_ONE, 'EmployeeDraft', 'idPerson'), // the relation for first employee
                        'firstProfessor' => array(self::HAS_ONE, 'ProfessorDraft', 'idPerson'), // the relation for first professor
                        'firstStudent' => array(self::HAS_ONE, 'StudentDraft', 'idPerson'), // the relation for first student     
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'firstName' => 'Primeiro Nome',
			'middleName' => 'Nome do meio',
			'lastName' => 'Sobrenome',
			'birthDate' => 'Data de nascimento',
			'deathDate' => 'Data de falecimento',
			'contact' => 'Contato',
			'career' => 'Carreira',
			'observations' => 'Observações',
			'priority' => 'Prioridade',
                        'verifyCode'=>'Código de verificação',
                        
                        
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{

		$criteria=new CDbCriteria;
                
		$criteria->compare('id',$this->id);
		$criteria->compare('firstName',$this->firstName,true);
		$criteria->compare('middleName',$this->middleName,true);
		$criteria->compare('lastName',$this->lastName,true);
		$criteria->compare('birthDate',$this->birthDate,true);
		$criteria->compare('deathDate',$this->deathDate,true);
		$criteria->compare('contact',$this->contact,true);
		$criteria->compare('career',$this->career,true);
		$criteria->compare('observations',$this->observations,true);
		$criteria->compare('priority',$this->priority);
                
                $criteria->compare('firstName',$this->name_search,true,"OR");
                $criteria->compare('middleName',$this->name_search,true,"OR");
                $criteria->compare('lastName',$this->name_search,true,"OR");
                
                //echo $this->is_student;
                if ($this->is_student == '1' ) {
                    $criteria->compare('is_student',1);
                } else if ($this->is_student == '0' ) {
                    $criteria->compare('is_student',0);
                }
                
                if ($this->is_professor == '1') {
                    $criteria->compare('is_professor',1);
                } else if ($this->is_professor == '0' ) {
                    $criteria->compare('is_professor',0);
                }
                
                if ($this->is_employee == '1') {
                    $criteria->compare('is_employee',1);
                } else if ($this->is_employee == '0' ) {
                    $criteria->compare('is_employee',0);
                }
                
		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
                        'sort'=>array(
                            'attributes'=>array(
                                'name_search'=>array(
                                    'asc'=>'firstName',
                                    'desc'=>'firstName DESC',
                                ),
                                '*',
                            ),
                        ),
                        
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return PersonDraft the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/PersonController.php
<?php

class PersonController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','createfromdraft','admin','delete'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
                if (Yii::app()->user->isGuest){
                $this->layout='//layouts/column1';
                }
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
                if (Yii::app()->user->isGuest){
                $this->layout='//layouts/column2';
                }
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Person;
                $student = new Student;
                $employee = new Employee;
                $professor = new Professor;
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
                
                $return = false;
                
                if(isset($_POST['Person'])) {
                    $model->attributes=$_POST['Person'];
                    $professor->attributes=$_POST['Professor'];
                    $student->attributes=$_POST['Student'];
                    $employee->attributes=$_POST['Employee'];
                    $student->isValid = $_POST['Student']['isValid'];
                    $professor->isValid = $_POST['Professor']['isValid'];
                    $employee->isValid = $_POST['Employee']['isValid'];
                    
                    if ($model->validate()) {
                            
                        if (strcmp($student->isValid,'1')==0) {
                            if($student->validate()) { 
                                $saveable['0']= $student; 
                                $model->is_student = true;
                            } else {
                                $return = true;
                                Yii::app()->user->setFlash('error1', '<strong>Erro nas informações de Aluno!</strong> Confira os dados específicos.');

                            }
                        }
                        if (strcmp($professor->isValid,'1')==0) {
                            if($professor->validate()) { 
                                $saveable['1']= $professor;  
                                $model->is_professor = true;
                            } else {
                                $return = true;
                                Yii::app()->user->setFlash('error2', '<strong>Erro nas informações de Professor!</strong> Confira os dados específicos.');
                            }
                        }
                        if (strcmp($employee->isValid,'1')==0) {
                            if($employee->validate()) { 
                                $saveable['2']= $employee; 
                                $model->is_employee = true;
                            } else {
                                $return = true;
                                Yii::app()->user->setFlash('error3', '<strong>Erro nas informações de Funcionário!</strong> Confira os dados específicos.');
                            }
                        }
                        
                        if (isset($saveable)) {
                            if ($return == false) {
                                $connection=Yii::app()->db;
                                $transaction=$connection->beginTransaction();
                                try{
                                    $model->save();

                                    if (isset($saveable['0'])){
                                        $student->idPerson = $model->id;
                                        $student->save();
                                    }
                                    if (isset($saveable['1'])){
                                        $professor->idPerson = $model->id;
                                        $professor->save();
                                    }
                                    if (isset($saveable['2'])){
                                        $employee->idPerson = $model->id;
                                        $employee->save();
                                    }
                                    $transaction->commit();
                                    Yii::app()->user->setFlash('success', '<strong>Pessoa salva com sucesso!</strong>');
                                }catch(Exception $e) // an exception is raised if a query fails
                                {
                                    $transaction->rollback();
                                }
                                
                                $this->redirect(array('view','id'=>$model->id));
                            } 
                        } else {
                                if ($return == false) Yii::app()->user->setFlash('error', '<strong>Erro!</strong> Você precisa habilitar pelo menos um: aluno, funcionário ou professor.');
                            }
                            
                    }
    
                }
		$this->render('create',array(
			'model'=>$model,
                        'student' => $student,
                        'professor' => $professor,
                        'employee' => $employee,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
                if (isset($model->students[0])) {
                    $student = $model->students[0];
                    $student->isValid = 1;
                } else {
                    $student = new Student();
                }
                               
                if (isset($model->professors[0])) {
                    $professor = $model->professors[0];
                    $professor->isValid = 1;
                } else {
                    $professor = new Professor();
                }
                
                if (isset($model->employees[0])) {
                    $employee = $model->employees[0];
                    $employee->isValid = 1;
                } else {
                    $employee = new Employee();
                }
                

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		$return = false;
                
                if(isset($_POST['Person'])) {
                    $model->attributes=$_POST['Person'];
                    $professor->attributes=$_POST['Professor'];
                    $student->attributes=$_POST['Student'];
                    $employee->attributes=$_POST['Employee'];
                    $student->isValid = $_POST['Student']['isValid'];
                    $professor->isValid = $_POST['Professor']['isValid'];
                    $employee->isValid = $_POST['Employee']['isValid'];
                    
                    if ($model->validate()) {
                            
                        if (strcmp($student->isValid,'1')==0) {
                            if($student->validate()) { 
                                $saveable['0']= $student;  
                                $model->is_student = true;
                            } else {
                                $return = true;
                                Yii::app()->user->setFlash('error1', '<strong>Erro nas informações de Aluno!</strong> Confira os dados específicos.');
                            }
                        } else {
                             if (isset($model->students[0])) {
                                 $model->students[0]->delete();
                                 $model->is_student = false;
                             }
                         }
                         
                        if (strcmp($professor->isValid,'1')==0) {
                            if($professor->validate()) { 
                                $saveable['1']= $professor;  
                                $model->is_professor = true;
                            } else {
                                $return = true;
                                Yii::app()->user->setFlash('error2', '<strong>Erro nas informações de Professor!</strong> Confira os dados específicos.');
                            }
                        } else {
                             if (isset($model->professors[0])) {
                                 $model->professors[0]->delete();
                                 $model->is_professor = false;
                             }
                         }
                         
                        if (strcmp($employee->isValid,'1')==0) {
                            if($employee->validate()) { 
                                $saveable['2']= $employee;  

protected/views/personDraft/_form_employee.php
<h3>Funcionário</h3>
<?php echo $form->toggleButtonRow($employee, 'isValid') ?>
<?php echo $form->datepickerRow($employee, 'enterDate',
array('hint'=>'Clique dentro para abrir o calendário',
'prepend'=>'<i class="icon-calendar"></i>',
'options'=>array('format'=>'dd/mm/yyyy'))); ?>
<?php echo $form->datepickerRow($employee, 'exitDate',
array('hint'=>'Clique dentro para abrir o calendário',
'prepend'=>'<i class="icon-calendar"></i>',
'options'=>array('format'=>'dd/mm/yyyy'))); ?>    
<?php echo $form->textFieldRow($employee, 'academicFormation'); ?>
<?php echo $form->textFieldRow($employee, 'department'); ?>
<?php echo $form->textFieldRow($employee, 'job'); ?>
<?php echo $form->textFieldRow($employee, 'registry'); ?>

protected/views/personDraft/_form_professor.php
<h3>Professor</h3>
<?php echo $form->toggleButtonRow($professor, 'isValid') ?>
<?php echo $form->datepickerRow($professor, 'enterDate',
array('hint'=>'Clique dentro para abrir o calendário',
'prepend'=>'<i class="icon-calendar"></i>',
'options'=>array('format'=>'dd/mm/yyyy'))); ?>
<?php echo $form->datepickerRow($professor, 'exitDate',
array('hint'=>'Clique dentro para abrir o calendário',
'prepend'=>'<i class="icon-calendar"></i>',
'options'=>array('format'=>'dd/mm/yyyy'))); ?>    
<?php echo $form->textFieldRow($professor, 'academicFormation'); ?>
<?php echo $form->textFieldRow($professor, 'researchArea'); ?>
<?php echo $form->textFieldRow($professor, 'department'); ?>
<?php echo $form->textFieldRow($professor, 'registry'); ?>

protected/views/personDraft/_form_student.php
<h3>Aluno</h3>
<?php echo $form->toggleButtonRow($student, 'isValid') ?>
<?php echo $form->datepickerRow($student, 'enterDate',
array('hint'=>'Clique dentro para abrir o calendário',
'prepend'=>'<i class="icon-calendar"></i>',
'options'=>array('format'=>'dd/mm/yyyy'))); ?>
<?php echo $form->datepickerRow($student, 'exitDate',
array('hint'=>'Clique dentro para abrir o calendário',
'prepend'=>'<i class="icon-calendar"></i>',
'options'=>array('format'=>'dd/mm/yyyy'))); ?>
<?php echo $form->textFieldRow($student, 'nickname'); ?>
<?php echo $form->textFieldRow($student, 'course',
array('hint'=>'No caso de mais de um curso, separá-los por ponto e vírgula.')); ?>
<?php echo $form->textFieldRow($student, 'class',
array('hint'=>'Informe o ano em que iniciou o curso (ex. 2009,2010..) 
    na ordem em que foram apresentados acima e separados por ponto e vírgula.')); ?>
<?php echo $form->textFieldRow($student, 'academicEntities'); ?>
<?php echo $form->textFieldRow($student, 'ra'); ?>

protected/views/personDraft/_newform.php
<?php /** @var BootActiveForm $form */
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id'=>'persondraft-form',
    'type'=>'horizontal',
)); ?>
<?php
$this->widget('bootstrap.widgets.TbAlert', array(
    'block'=>true, // display a larger alert block?
    'fade'=>true, // use transitions?
    'closeText'=>'×', // close link text - if set to false, no close link is displayed
    'alerts'=>array( // configurations per alert type
	    'warning'=>array('block'=>true, 'fade'=>true, 'closeText'=>'×'), // success, info, warning, error or danger
            'error'=>array('block'=>true, 'fade'=>true, 'closeText'=>'×'),
            'error1'=>array('block'=>true, 'fade'=>true, 'closeText'=>'×'),
            'error2'=>array('block'=>true, 'fade'=>true, 'closeText'=>'×'),
            'error3'=>array('block'=>true, 'fade'=>true, 'closeText'=>'×'),
        ),
));

?>
 
<fieldset>
 
    <legend>Informações gerais</legend>


    <?php echo $form->textFieldRow($model, 'firstName'); ?>
    <?php echo $form->textFieldRow($model, 'middleName'); ?>
    <?php echo $form->textFieldRow($model, 'lastName'); ?>         
    <?php echo $form->datepickerRow($model, 'birthDate',
        array('hint'=>'Clique dentro para abrir o calendário',
        'prepend'=>'<i class="icon-calendar"></i>',
        'options'=>array('format'=>'dd/mm/yyyy'))); ?>
    <?php echo $form->datepickerRow($model, 'deathDate',
        array('hint'=>'Clique dentro para abrir o calendário',
        'prepend'=>'<i class="icon-calendar"></i>',
        'options'=>array('format'=>'dd/mm/yyyy'))); ?>
    <?php echo $form->textFieldRow($model, 'contact'); ?>
    <?php echo $form->redactorRow($model, 'career', array('class'=>'span8', 'rows'=>5)); ?>
    <?php echo $form->redactorRow($model, 'observations', array('class'=>'span8', 'rows'=>5)); ?>

    <legend>Informações específicas</legend>
    
 <?php $this->widget('bootstrap.widgets.TbTabs', array(
    'type'=>'tabs', 
     'tabs'=>array(
        array('label'=>'Aluno', 'content'=>$this->renderPartial('_form_student', array('student'=>$student,'form'=>$form ),true)),
        array('label'=>'Professor', 'content'=>$this->renderPartial('_form_professor', array('professor'=>$professor,'form'=>$form),true), 'active' =>true),
        array('label'=>'Funcionário', 'content'=>$this->renderPartial('_form_employee', array('employee'=>$employee,'form'=>$form),true)),
    ),
)); ?>
    
    <legend>Confirmação</legend>
  
    <?php if(CCaptcha::checkRequirements()): ?>
    <div class="row" style="margin-left: 30px">
            <?php echo $form->labelEx($model,'verifyCode'); ?>
            <div>
            <?php $this->widget('CCaptcha'); ?>
            <?php echo $form->textField($model,'verifyCode'); ?>
            </div>
            <div class="hint">Please enter the letters as they are shown in the image above.
            <br/>Letters are not case-sensitive.</div>
            <?php echo $form->error($model,'verifyCode'); ?>
    </div>
    <?php endif; ?>  
    
</fieldset>




<div class="form-actions">
    <?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'submit', 'type'=>'primary', 'label'=>'Enviar')); ?>
    <?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'reset', 'label'=>'Limpar campos')); ?>
</div>
 
<?php $this->endWidget(); ?>

protected/views/personDraft/create.php
<?php
/* @var $this PersonController */
/* @var $model Person 
 * @var $student Student
 * @var $employee Employee
 * @var $professor Professor
 */

$this->breadcrumbs=array(
	'Contribuições'=>array('site/contributions'),
	'Pessoa',
);

?>

<h1>Enviar contribuição de Pessoa</h1>


<?php $this->renderPartial('_newform', array('model'=>$model,'student'=>$student, 'professor'=>$professor, 'employee'=>$employee)); ?>

protected/views/personDraft/index.php
<?php
/* @var $this PersonController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Contribuições',
);

?>

<h1>Contribuições para aprovação</h1>
<h2>Pessoas</h2>

<?php
$this->widget('bootstrap.widgets.TbAlert', array(
    'block'=>true, // display a larger alert block?
    'fade'=>true, // use transitions?
    'closeText'=>'×', // close link text - if set to false, no close link is displayed
    'alerts'=>array( // configurations per alert type
	    'success'=>array('block'=>true, 'fade'=>true, 'closeText'=>'×'),
        ),
)); 
?>

<?php /*$this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); */

$this->widget('bootstrap.widgets.TbGridView', array(
        'type'=>'striped bordered condensed',
	'dataProvider'=>$model->search(),
        'emptyText'=>"Não há pessoas que satisfaçam essa busca.",
        'summaryText'=>'Total: {count}',
	//'template'=>"{items}",
	'filter'=>$model,
	'columns'=>array(
            
              array(
                    'name'=>'name_search',
                    'header' => 'Nome',
                    'value'=>'$data->firstName . " " . $data->middleName . " " . $data->lastName', 
                ),
            
		//'id',
		//'firstName',
		//'middleName',
		//'lastName',
                'contact',
                //'is_student',
            
      
            
                array(
                    'name'=>'is_student',
                    'header' => 'Aluno',
                    'value'=>'isset(StudentDraft::Model()->findByAttributes(array("idPerson"=>$data->id))->class) ? "sim" : "não"', 
                    //// causes 'Trying to get property of non-object' - no error if $data->city
                     'filter'=>CHtml::activeDropDownList($model, 'is_student', array('2' => 'todos','0' => 'não', '1' => 'sim')),
                    //'filter'=>CHtml::activeDropDownList
                    //'value'=>'CHtml::checkBox("is_student",null,array("value"=>$data->id,"id"=>"cid_".$data->id))',
                    ),
            
                array(
                    'name'=>'is_employee',
                    'header' => 'Funcionário',
                    'value'=>'isset(EmployeeDraft::Model()->findByAttributes(array("idPerson"=>$data->id))->job) ? "sim" : "não"', 
                    //// causes 'Trying to get property of non-object' - no error if $data->city
                     'filter'=>CHtml::activeDropDownList($model, 'is_employee', array('2' => 'todos','0' => 'não', '1' => 'sim')),
                    ),
            
               array(
                    'name'=>'is_professor',
                    'header' => 'Professor',
                    'value'=>'isset(ProfessorDraft::Model()->findByAttributes(array("idPerson"=>$data->id))->registry) ? "sim" : "não"', 
                    //// causes 'Trying to get property of non-object' - no error if $data->city
                     'filter'=>CHtml::activeDropDownList($model, 'is_professor', array('2' => 'todos','0' => 'não', '1' => 'sim')),
                    ), 
                 
                array(
                       'header' => 'Confirmar dados',
                       'class'=>'CButtonColumn',
                       'template'=>'{view}',
                       'buttons'=>array(
                           'view'=>array(
                               'url'=>'Yii::app()->createUrl("person/createfromdraft",array("id"=>$data->id))',
                           )
                       )
                   ),
                array(
                       'header' => 'Rejeitar',
                       'class'=>'CButtonColumn',
                       'template'=>'{delete}',
                       'buttons'=>array(
                           'view'=>array(
                               'url'=>'Yii::app()->createUrl("personDraft/delete",array("id"=>$data->id))',
                           )
                       )
                   ),
            ),
    
));


?>
<br>
<br>
<h2>Depoimentos</h2>
<br>

<?php 
    $testimonials = Testimonials::model()->findAll('isVisible = 0');

    foreach ($testimonials as $test) {
        $person = Person::model()->find('id = ' . $test->idPerson );
        $this->widget('bootstrap.widgets.TbBox', array(
            'title' => 'Depoimento enviado por  "' . $test->name . '"  para ' . 
            CHtml::link($person->firstName . ' ' . $person->lastName,Yii::app()->createUrl ("/person/view",array("id"=>$data->id))) .
                ' em ' .$test->date . ' <div style="position: absolute;right: -350px;top: 0;">'.
            CHtml::link('Aceitar',Yii::app()->createUrl ("personDraft/AcceptTestimonials",array("id"=>$test->id)), array("style"=>"color:green")) . '' .
            '  ou  '.
            CHtml::link('Deletar',Yii::app()->createUrl ("personDraft/deleteTestimonials",array("id"=>$test->id)), array("style"=>"color:red")) . '</div>',
            'headerIcon' => 'icon-list-alt',
            'content' => $test->text,
        )); 

    }
?>